// <auto-generated />
namespace Ca1_RAD_302.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first));
        
        string IMigrationMetadata.Id
        {
            get { return "201603222115183_first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
